apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-multi-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/jayasree-k/Argo_trianing.git
      targetRevision: HEAD
      path: App-resources/multi-git-src
    - repoURL: https://github.com/jayasree-k/Argo_trianing.git
      targetRevision: HEAD
      path: App-resources/multi-git-src
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
